# Generated by Django 5.2.14 on 2026-05-07 15:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='price_adjustment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=170, unique=True)),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['slug'], name='catalog_var_slug_521583_idx'), models.Index(fields=['is_active'], name='catalog_var_is_acti_7b453d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductVariationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_default', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.variation')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='available_variations',
            field=models.ManyToManyField(blank=True, related_name='products', through='catalog.ProductVariationLink', to='catalog.variation'),
        ),
        migrations.AddIndex(
            model_name='productvariationlink',
            index=models.Index(fields=['product', 'variation'], name='catalog_pro_product_55be33_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariationlink',
            index=models.Index(fields=['is_default'], name='catalog_pro_is_defa_d2b363_idx'),
        ),
        migrations.AddConstraint(
            model_name='productvariationlink',
            constraint=models.UniqueConstraint(fields=('product', 'variation'), name='uniq_product_variation_link'),
        ),
    ]
