# Generated by Django 5.2.14 on 2026-05-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_category_price_adjustment_variation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_most_sold',
            field=models.BooleanField(default=False),
        ),
    ]
